# Generated by Django 2.1.4 on 2019-01-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Введите вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Cand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50)),
                ('age', models.IntegerField(help_text='Сколько вам лет?')),
                ('email', models.EmailField(help_text='ivanov@gmail.com', max_length=254)),
                ('num_answer', models.IntegerField(help_text='Количество правильных ответов', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(help_text='Введите планету', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jedi',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Planet'),
        ),
        migrations.AddField(
            model_name='cand',
            name='his_jedi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Jedi'),
        ),
        migrations.AddField(
            model_name='cand',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Planet'),
        ),
    ]
